[package]
name = "thedestroyercam/physics-tween-service"
description = "a physics based tween system"
version = "0.1.4"
license = "MIT"
authors = ["Cameron Smith <DestroyerCam1@gmail.com>"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"


